### ISSUE TITLE
bentham*LookaheadTop and egoist*LookaheadTop broken

### ISSUE THREAD

**Issue by nkremerh** [nkremerh/sugarscape#19]
The behavior of the `bentham*LookaheadTop` and `egoist*LookaheadTop` decision models appears broken on first glance. Any model ending in `Top` should be selecting the locally optimum choice, yet this seems to always result in quick societal death during data collection (while the more naive `Binary` models do not). There is likely a logic bug that needs to be diagnosed and patched. Another avenue worth investigating is if the configuration options used during data collection prevent the `Top` models from making good choices.

**Comment by nkremerh** [comment]
Maybe fixed due to many code changes to agent decision model behavior. Will need to verify.

**Comment by colinhanrahan** [comment]
I had a hard time reproducing this as well.

**Comment by nkremerh** [comment]
Nevermind. When running the simulation out to 750 timesteps over 20 seeds, I get the following report:

```
        Decision Model         Died  Worse Better
    benthamNoLookaheadTop     :  20     0     0  
    egoisticNoLookaheadTop    :  20     0     0  
   benthamNoLookaheadBinary   :   0     0    20  
  egoisticNoLookaheadBinary   :  12     0     8  
        rawSugarscape         :  12     0     8
```

**Comment by nkremerh** [comment]
Same configuration while using the half lookahead decision models:

```
        Decision Model         Died  Worse Better
   benthamHalfLookaheadTop    :   1     0    19  
   egoisticHalfLookaheadTop   :   6     0    14  
  benthamHalfLookaheadBinary  :   0     0    20  
 egoisticHalfLookaheadBinary  :  10     1     9  
        rawSugarscape         :  15     0     5
```

**Comment by colinhanrahan** [comment]
The only difference I can find for 'Top' models is the 'Top' check and subsequent sort in 'findBestEthicalCell()', which looks fine. My best guess is that some part of the ethical calculation is incorrect for certain cells. For example, maybe duration is incorrect for neighbors with 0 metabolism, or intensity is incorrect for really old agents. As an effect of this, a few cells are incorrectly calculated to have really high ethical scores, so they are chosen as the best cells when we are getting the best value for 'Top'. For binary models, it'll usually choose a correctly calculated cell by chance.

I'm not familiar enough with the ethical formula as implemented in the repo to check if these are all correct, but maybe other people working on the issue will find this useful.

**Comment by colinhanrahan** [comment]
Setting `certainty` to 1 (removing it from the equation) _does_ improve the survival of `*Top` models but causes interesting clumping behavior and a relatively unsuccessful population over time (~200 agents, sometimes increasing or decreasing).
![Screenshot 2024-02-28 9 02 52 PM](https://github.com/nkremerh/sugarscape/assets/118491522/82cb0981-de43-49dd-9b46-75c4193410cf)
It might be worth running a larger test with `certainty` removed just to see what happens.

**Comment by colinhanrahan** [comment]
I think I figured something out. Picture a cardinal agent with 3 agents in the neighborhood on the vertical axis and 0 agents on the horizontal axis. For any cell on the vertical axis, those other agents might be able to move there, so you'll get opportunity costs from all of them and subtract from the ethical score of the cell. However, none of the agents on the vertical axis can see any of the cells on the horizontal axis, so the opportunity costs will be 0. So opportunity costs incentivize agents to "stay out of each other's sights." Even with radial vision and movement, I think agents will be hesitant to get too close to each other (using `*Top` decision) because opportunity costs from other close agents will outweigh the benefits of the cell, encouraging agents to move out of other agents' visions. Using a `*Binary` model, agents will be von Neumann neighbors to each other more often just by random chance, spawning more children overall.

Out of curiosity, I just tried removing opportunity costs (removing the multiplications by -1, everything else is the same) and my `*Top` model was very successful. I don't fully understand why, given that the calculated `neighborValueOfCell`s are not real and will not ever be real for the neighbor. Maybe it's closer to egoism — a decent cell with sugar and spice would be good for any agent, so it's good for the current agent?

Logically, opportunity costs should not be removed. However, I'm concerned that the current felicific calculus inherently encourage agents to stay away from each other, because we are not considering the positive effects of closeness and von Neumann neighbors like trading and reproduction. I think that the interaction between opportunity costs and reproduction should be changed in order to ensure the success of `*Top` models. Something like a fully implemented `findPotentialNiceOfCell()` would probably better demonstrate `*Top`'s abilities.

**Comment by nkremerh** [comment]
Update on this after the plethora of changes this summer:

```
Model population performance:
        Decision Model         Extinct Worse Better
        benthamBinary         :   4     0    196 
          benthamTop          :  40     0    160
```

The `Top` model doesn't seem as absolutely self-destructive as before. The average population was around 600 for `Top` (around 800 if you don't count the extinct societies) while around 1,100 for `Binary` (same when counting extinct societies, we were unlucky with those 4 seeds, it's usually 0 or 1 extinction per 100 seeds).

I will perform the same experiment and crank up the `selfishnessFactor` to 75% to see if that's necessary for the `Top` model to dominate. Looking at the graphs without counting the extinctions, the `Top` model performs very slightly above the `Binary` model in all but population.
